// types/supabase.ts
// ============================================================
// AUTO-GENERATED by: npm run db:generate
// Do NOT edit manually — run the command above after
// making schema changes in Supabase dashboard.
// ============================================================

export type Json =
  | string
  | number
  | boolean 
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // ── Properties ─────────────────────────────────────
      properties: {
        Row: {
          id: string;
          title: string;
          slug: string;
          type: string;
          status: string;
          listing_type: string;
          price: number;
          price_currency: string;
          bedrooms: number | null;
          bathrooms: number;
          area_sqft: number;
          location: string;
          community: string;
          developer: string | null;
          furnishing: string;
          description: string;
          features: string[];
          images: string[];
          featured: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          title: string;
          slug: string;
          type: string;
          status: string;
          listing_type: string;
          price: number;
          price_currency: string;
          bedrooms?: number | null;
          bathrooms: number;
          area_sqft: number;
          location: string;
          community: string;
          developer?: string | null;
          furnishing: string;
          description: string;
          features: string[];
          images: string[];
          featured: boolean;
        };
        Update: {
          title?: string;
          slug?: string;
          type?: string;
          status?: string;
          listing_type?: string;
          price?: number;
          price_currency?: string;
          bedrooms?: number | null;
          bathrooms?: number;
          area_sqft?: number;
          location?: string;
          community?: string;
          developer?: string | null;
          furnishing?: string;
          description?: string;
          features?: string[];
          images?: string[];
          featured?: boolean;
        };
      };

      // ── Leads ──────────────────────────────────────────
      leads: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          message: string | null;
          source: string;
          property_id: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          name: string;
          email: string;
          phone: string;
          message?: string | null;
          source: string;
          property_id?: string | null;
          status: string;
        };
        Update: {
          name?: string;
          email?: string;
          phone?: string;
          message?: string | null;
          source?: string;
          property_id?: string | null;
          status?: string;
        };
      };

      // ── Subscribers ────────────────────────────────────
      subscribers: {
        Row: {
          id: string;
          email: string;
          created_at: string;
        };
        Insert: {
          email: string;
        };
        Update: {
          email?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
