import React from 'react';
import { 
  Waves, Dumbbell, Bell, Flame, Activity, Droplets, Users, 
  Car, Leaf, Building2, Target, Thermometer, Briefcase, 
  Film, Shield, Check, Wind, Coffee, Utensils, Bike, 
  Sparkles, Heart, Trees, Map as MapIcon, Wifi, Tv,
  ShoppingBag, Gamepad2, Ticket
} from 'lucide-react';

export const AMENITY_ICON_MAP: Record<string, React.ElementType> = {
  pool: Waves, 
  "swimming pool": Waves, 
  "infinity pool": Waves,
  "swimming pool and toddler’s pool": Waves,
  gym: Dumbbell, 
  fitness: Dumbbell,
  spa: Bell, 
  "spa and jacuzzi": Waves,
  concierge: Bell,
  "bbq": Flame, 
  "bbq area": Flame,
  jogging: Activity, 
  "jogging track": Activity, 
  "running track": Activity,
  "kids pool": Droplets, 
  "kids' pool": Droplets, 
  "dedicated kids' pool": Droplets,
  "function room": Users,
  "clubhouse": Users,
  "terrace area for events": Users,
  parking: Car, 
  "covered parking": Car, 
  "valet parking": Car,
  garden: Leaf, 
  nature: Leaf,
  "beach access": Waves, 
  beach: Waves, 
  "lagoon access": Waves,
  "rooftop": Building2, 
  "rooftop terrace": Building2,
  tennis: Target, 
  "tennis court": Target,
  "tennis court & basketball court": Target,
  "squash court": Target,
  "cricket pitch": Activity,
  "table tennis": Target,
  "skating rink": Activity,
  sauna: Thermometer,
  "business center": Briefcase,
  cinema: Film, 
  "cinema room": Film,
  "mini theater": Film,
  security: Shield,
  "ac": Wind,
  "central ac": Wind,
  "cafe": Coffee,
  "restaurant": Utensils,
  "cycling track": Bike,
  "luxury lobby": Sparkles,
  "yoga": Heart,
  "yoga centre": Heart,
  "park": Trees,
  "landscaped": Trees,
  "multiple kids play areas": Trees,
  "open roof garden": Trees,
  "elaborate terrace garden": Trees,
  "multi-indoor games facilities": Gamepad2,
  "board games": Gamepad2,
  "billiards and pool": Target,
  "shopping centre adjacent to the clubhouse": ShoppingBag,
  "wifi": Wifi,
  "satellite": Tv,
};

export function AmenityIcon({ name, size = 16 }: { name: string, size?: number }) {
  const Icon = AMENITY_ICON_MAP[name.toLowerCase()] ?? Check;
  return <Icon size={size} strokeWidth={1.5} className="text-black/50 shrink-0" />;
}
