import type { Property } from "@/types";

export const DEMO_PROPERTIES: Property[] = [
  {
    id: "demo-1",
    title: "The Alba Residences",
    slug: "the-alba-residences",
    type: "apartment",
    status: "off-plan",
    listing_type: "off-plan",
    price: 0,
    price_currency: "AED",
    bedrooms: 1,
    bedrooms_max: 3,
    bathrooms: 2,
    area_sqft: 1640,
    location: "Dubai Marina",
    community: "Dubai Marina",
    developer: "OMNIYAT",
    developer_website: "https://omniyat.com",
    furnishing: "furnished",
    description:
      "The Alba Residences is an ultra-luxury development managed by the Dorchester Collection in the heart of Dubai Marina. Breathtaking sea views, private plunge pools, and bespoke concierge services define this landmark address. Each residence is crafted with Italian marble, bespoke joinery, and floor-to-ceiling windows framing the Arabian Gulf.",
    features: ["Sea View", "Private Pool", "Concierge", "Gym", "Spa", "Valet Parking"],
    images: [
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200",
      "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
    ],
    image_count: 14,
    featured: true,
    building_name: "The Alba",
    address: "Dubai Marina, Dubai, United Arab Emirates",
    highlights: [
      "Managed by Dorchester Collection — world-class hotel operator",
      "Private plunge pools on select residences",
      "Panoramic views of the Arabian Gulf and Dubai Marina skyline",
      "Floor-to-ceiling windows in all living spaces",
      "Bespoke Italian kitchen with Miele appliances",
      "24-hour concierge and butler service",
      "Direct access to marina promenade and beach",
      "Smart home automation throughout",
      "Private residents' lounge and rooftop terrace",
      "Dedicated valet parking and EV charging stations",
      "Close proximity to JBR Beach and The Walk",
      "5-minute drive to Dubai Internet City Metro Station",
    ],
    amenities: [
      "Infinity Pool",
      "Gym",
      "Spa",
      "Concierge",
      "Covered Parking",
      "Beach Access",
      "Rooftop Terrace",
      "Business Center",
      "Sauna",
      "Cinema Room",
      "BBQ Area",
      "Garden",
    ],
    interior_features: [
      "Italian marble throughout",
      "Floor-to-ceiling windows",
      "Bespoke kitchen with Miele appliances",
      "Custom wardrobes and joinery",
    ],
    nearby_landmarks: [
      { name: "JBR Beach", time: 5, transport: "walk" },
      { name: "Dubai Marina Mall", time: 8, transport: "walk" },
      { name: "Dubai Internet City Metro", time: 5, transport: "car" },
      { name: "Palm Jumeirah", time: 10, transport: "car" },
      { name: "Dubai International Airport", time: 35, transport: "car" },
      { name: "Downtown Dubai", time: 20, transport: "car" },
    ],
    latitude: 25.0805,
    longitude: 55.1403,
    payment_plan: {
      down_payment: 10,
      during_construction: 70,
      on_handover: 20,
    },
    documents: [
      { name: "Floor Plan Download", coming_soon: true },
      { name: "Documents & Brochure", url: "#", coming_soon: false },
      { name: "Terms & Conditions", coming_soon: true },
    ],
    unit_types_image:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
    unit_types_coming_soon: true,
    agent_name: "Armina Crnovsanin",
    agent_title: "CEO",
    agent_email: "armina@monterealestate.ae",
    agent_phone: "+971 58 529 8618",
    agent_photo:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
    agent_languages: ["German", "English"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    title: "Creek Horizon Tower",
    slug: "creek-horizon-tower",
    type: "apartment",
    status: "off-plan",
    listing_type: "off-plan",
    price: 1490000,
    price_currency: "AED",
    bedrooms: 1,
    bedrooms_max: 2,
    bathrooms: 2,
    area_sqft: 780,
    location: "Dubai Creek Harbour",
    community: "Creek Harbour",
    developer: "Emaar Properties",
    developer_website: "https://emaar.com",
    furnishing: "unfurnished",
    description:
      "Contemporary residences overlooking the iconic Dubai Creek Tower in the heart of Creek Harbour. Premium finishes, smart home technology, and world-class amenities make this an exceptional investment opportunity in one of Dubai's fastest-growing neighbourhoods.",
    features: ["Creek View", "Smart Home", "Infinity Pool", "Rooftop Terrace"],
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200",
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
      "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200",
    ],
    image_count: 8,
    featured: false,
    building_name: "Creek Horizon",
    address: "Creek Harbour, Dubai, United Arab Emirates",
    highlights: [
      "Stunning views of Dubai Creek Tower and the Creek",
      "Smart home automation in every residence",
      "Resort-style amenities across multiple floors",
      "Walking distance to Creek Marina and waterfront dining",
      "Emaar's trademark quality and on-time delivery",
      "Flexible post-handover payment plans available",
      "Close to Dubai International Airport (15 min)",
      "Metro connectivity planned for 2026",
    ],
    amenities: [
      "Infinity Pool",
      "Gym",
      "Rooftop Terrace",
      "Covered Parking",
      "Garden",
      "BBQ Area",
      "Tennis Court",
      "Kids Pool",
    ],
    interior_features: [
      "Contemporary design",
      "Neutral material palette",
      "Smart home integration",
      "Open-plan layouts",
    ],
    nearby_landmarks: [
      { name: "Dubai Creek Tower", time: 5, transport: "walk" },
      { name: "Creek Marina", time: 8, transport: "walk" },
      { name: "Dubai International Airport", time: 15, transport: "car" },
      { name: "Downtown Dubai", time: 15, transport: "car" },
      { name: "DIFC", time: 18, transport: "car" },
    ],
    latitude: 25.2024,
    longitude: 55.349,
    payment_plan: {
      down_payment: 10,
      during_construction: 60,
      on_handover: 30,
    },
    documents: [
      { name: "Floor Plan Download", url: "#", coming_soon: false },
      { name: "Documents & Brochure", url: "#", coming_soon: false },
      { name: "Terms & Conditions", coming_soon: true },
    ],
    unit_types_image:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
    unit_types_coming_soon: false,
    agent_name: "Armina Crnovsanin",
    agent_title: "CEO",
    agent_email: "armina@monterealestate.ae",
    agent_phone: "+971 58 529 8618",
    agent_photo:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
    agent_languages: ["German", "English"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    title: "Tilal Al Ghaf Villas",
    slug: "tilal-al-ghaf-villas",
    type: "villa",
    status: "off-plan",
    listing_type: "off-plan",
    price: 0,
    price_currency: "AED",
    bedrooms: 4,
    bedrooms_max: 6,
    bathrooms: 5,
    area_sqft: 4200,
    location: "Tilal Al Ghaf",
    community: "Tilal Al Ghaf",
    developer: "Majid Al Futtaim",
    developer_website: "https://majidalfuttaim.com",
    furnishing: "unfurnished",
    description:
      "Exclusive lakeside villas in Tilal Al Ghaf, Dubai's newest master-planned lifestyle destination. Set around a 70,000 sqm crystal lagoon, these villas offer private gardens, lagoon access, and resort-style amenities in a fully integrated community.",
    features: [
      "Lagoon Access",
      "Private Garden",
      "Maid's Room",
      "4-Car Garage",
      "Smart Home",
      "Community Pool",
    ],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
      "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
    ],
    image_count: 11,
    featured: true,
    building_name: "Tilal Al Ghaf",
    address: "Tilal Al Ghaf, Dubai, United Arab Emirates",
    highlights: [
      "Direct lagoon access from private garden",
      "4–6 bedroom layouts across two floors",
      "Maid's room, driver's room, and storage included",
      "Private pool available on select plots",
      "Majid Al Futtaim's track record of on-time delivery",
      "Walking distance to Lagoon Al Ghaf beach club",
      "Schools and retail within the master community",
      "5-year post-handover payment plan available",
      "Central Dubai location with Sheikh Zayed Road access",
      "Solar-ready infrastructure for sustainable living",
    ],
    amenities: [
      "Lagoon Access",
      "Pool",
      "Gym",
      "Garden",
      "Tennis Court",
      "Kids Pool",
      "BBQ Area",
      "Jogging Track",
      "Business Center",
      "Covered Parking",
      "Beach Access",
    ],
    interior_features: [
      "Double-height ceilings in living areas",
      "Marble and engineered timber flooring",
      "Fully fitted kitchen with premium appliances",
      "Large windows and natural light focus",
    ],
    nearby_landmarks: [
      { name: "Sheikh Zayed Road", time: 5, transport: "car" },
      { name: "Mall of the Emirates", time: 15, transport: "car" },
      { name: "Downtown Dubai", time: 20, transport: "car" },
      { name: "Dubai International Airport", time: 25, transport: "car" },
      { name: "GEMS World Academy", time: 10, transport: "car" },
    ],
    latitude: 25.0352,
    longitude: 55.2338,
    payment_plan: {
      down_payment: 5,
      during_construction: 65,
      on_handover: 30,
    },
    documents: [
      { name: "Floor Plan Download", coming_soon: true },
      { name: "Documents & Brochure", url: "#", coming_soon: false },
      { name: "Terms & Conditions", coming_soon: true },
    ],
    unit_types_image:
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
    unit_types_coming_soon: true,
    agent_name: "Armina Crnovsanin",
    agent_title: "CEO",
    agent_email: "armina@monterealestate.ae",
    agent_phone: "+971 58 529 8618",
    agent_photo:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
    agent_languages: ["German", "English"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
