const fs = require('fs');

const allImages = [
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200",
  "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
  "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200",
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200",
  "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
  "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200",
  "https://images.unsplash.com/photo-1600585154526-990dced4ea0a?w=1200",
  "https://images.unsplash.com/photo-1600607687644-b04fd4d10d33?w=1200",
  "https://images.unsplash.com/photo-1600607688969-a5bfcd64bd28?w=1200",
  "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200",
  "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=1200",
  "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200",
  "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200",
  "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200",
  "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200",
  "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200"
];

function getRandomImages() {
  const shuffled = [...allImages].sort(() => 0.5 - Math.random());
  const count = Math.floor(Math.random() * (16 - 10 + 1)) + 10; // 10 to 16 images
  return shuffled.slice(0, count);
}

const projects = [
  {
    title: "Marbella Grand 3, 4 & 5 BHK Luxury Apartments",
    slug: "marbella-grand-it-city-mohali",
    type: "apartment",
    status: "available",
    listing_type: "sale",
    price: 32000000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 5,
    bathrooms: 4,
    area_sqft: 2600,
    location: "Mohali",
    community: "IT City",
    building_name: "Marbella Grand",
    developer: "Marbella Group",
    address: "IT City, Sector 82A, Mohali, Punjab",
    latitude: 30.6655,
    longitude: 76.7322,
    furnishing: "semi-furnished",
    description: "Marbella Grand offers ultra-luxury apartments, earth villas, and penthouses. Designed for those who appreciate fine living, it features unparalleled amenities including a skywalk, expansive clubhouses, and smart home technology. Located on Airport Road, offering prime connectivity.",
    features: ["Smart Home Automation", "Italian Marble Flooring", "Modular Kitchen", "VRV Air Conditioning"],
    highlights: ["Prime location on Airport Road", "Close to International Airport", "Upcoming IT Hub vicinity"],
    amenities: ["Swimming Pool", "Gym", "Spa", "Mini Theatre", "Tennis Court", "Kids Pool"],
    interior_features: ["Walk-in Closets", "Premium Bath Fittings", "Double-height Ceilings"],
    upcoming_infrastructure: ["Bharatmala connectivity", "New corporate offices in IT City"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: true
  },
  {
    title: "Noble Callista 3, 4 & 5 BHK Premium Residences",
    slug: "noble-callista-sector-66b-mohali",
    type: "apartment",
    status: "off-plan",
    listing_type: "sale",
    price: 38000000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 5,
    bathrooms: 4,
    area_sqft: 2850,
    location: "Mohali",
    community: "Sector 66B",
    building_name: "Noble Callista",
    developer: "Noble Ventures",
    address: "Sector 66B, IT City Road, Mohali",
    latitude: 30.6721,
    longitude: 76.7451,
    furnishing: "semi-furnished",
    description: "Noble Callista is a beacon of luxury living in Mohali, offering spacious 3, 4, and 5 BHK apartments. With a focus on sustainable and green living, it provides expansive balconies, top-tier clubhouse facilities, and seamless access to Chandigarh and the airport.",
    features: ["Green Building Design", "Grand Entrance Lobby", "Premium Wooden Flooring"],
    highlights: ["Immediate access to IT City", "Proximity to top schools", "High rental yield potential"],
    amenities: ["Infinity Pool", "Business Center", "Concierge", "Jogging Track", "Rooftop Terrace"],
    interior_features: ["Spacious Balconies", "Fitted Wardrobes", "Designer Kitchens"],
    upcoming_infrastructure: ["New commercial complexes", "Road widening project"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: true
  },
  {
    title: "Beverly Golf Avenue Luxury Condominiums",
    slug: "beverly-golf-avenue-sector-65-mohali",
    type: "apartment",
    status: "available",
    listing_type: "sale",
    price: 29000000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 4,
    bathrooms: 4,
    area_sqft: 2150,
    location: "Mohali",
    community: "Sector 65",
    building_name: "Beverly Golf Avenue",
    developer: "Beverly Golf Avenue",
    address: "Adjoining Mohali Golf Range, Sector 65, Mohali",
    latitude: 30.6883,
    longitude: 76.7384,
    furnishing: "semi-furnished",
    description: "Wake up to breathtaking views of the Mohali Golf Range. Beverly Golf Avenue combines opulence with nature, offering lavish condominiums with world-class clubhouse amenities and sports facilities right at your doorstep.",
    features: ["Golf Course Views", "Vaastu Compliant", "Earthquake Resistant Structure"],
    highlights: ["Direct access to Golf Range", "Central location", "Elite neighborhood"],
    amenities: ["Golf Putting", "Swimming Pool", "Gym", "Sauna", "BBQ Area"],
    interior_features: ["Large French Windows", "Branded Sanitary Ware", "Video Door Phone"],
    upcoming_infrastructure: ["Sector 65 Metro Station proposal", "Upgraded neighborhood parks"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: false
  },
  {
    title: "The Medallion Premium 3 & 4 BHK Apartments",
    slug: "the-medallion-sector-82a-mohali",
    type: "apartment",
    status: "off-plan",
    listing_type: "sale",
    price: 27500000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 4,
    bathrooms: 3,
    area_sqft: 1950,
    location: "Mohali",
    community: "Sector 82A",
    building_name: "The Medallion",
    developer: "Turnstone Realty",
    address: "Sector 82A, IT City, Mohali",
    latitude: 30.6612,
    longitude: 76.7301,
    furnishing: "semi-furnished",
    description: "The Medallion offers premium residential living with exclusive 3 and 4 BHK apartments and penthouses. Designed for optimal natural light and ventilation, it features dedicated green spaces, a massive clubhouse, and zero surface traffic design.",
    features: ["Podium Level Amenities", "No Surface Traffic", "Independent Towers"],
    highlights: ["Corner site", "Double-height podium", "Surrounded by IT corporate offices"],
    amenities: ["Kids Pool", "Tennis Court", "Function Room", "Gym", "Spa"],
    interior_features: ["Modular Kitchen with Chimney", "Premium Vitrified Tiles", "Concealed Wiring"],
    upcoming_infrastructure: ["IT City commercial expansion", "New airport road flyovers"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: true
  },
  {
    title: "Homeland Heights Ultra-Luxury Residences",
    slug: "homeland-heights-sector-70-mohali",
    type: "apartment",
    status: "available",
    listing_type: "sale",
    price: 45000000,
    price_currency: "INR",
    bedrooms: 4,
    bedrooms_max: 5,
    bathrooms: 5,
    area_sqft: 3200,
    location: "Mohali",
    community: "Sector 70",
    building_name: "Homeland Heights",
    developer: "Homeland Group",
    address: "Sector 70, Airport Road, Mohali",
    latitude: 30.7025,
    longitude: 76.7150,
    furnishing: "semi-furnished",
    description: "One of Mohali's most iconic luxury addresses. Homeland Heights sets a benchmark in architectural brilliance and luxury living. Featuring a soaring high-rise structure, these apartments offer panoramic city views, unmatched privacy, and top-of-the-line amenities.",
    features: ["Helipad", "Iconic High-rise", "Exquisite Landscaping"],
    highlights: ["Heart of Mohali", "Instant connectivity to Chandigarh", "Elite resident profile"],
    amenities: ["Infinity Pool", "Valet Parking", "Security", "Gym", "Business Center"],
    interior_features: ["Central Air Conditioning", "Imported Marble", "Servant Quarter"],
    upcoming_infrastructure: ["Premium retail high-street nearby"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: false
  },
  {
    title: "JLPL Falcon View Premium Apartments",
    slug: "jlpl-falcon-view-sector-66a-mohali",
    type: "apartment",
    status: "available",
    listing_type: "sale",
    price: 31000000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 4,
    bathrooms: 4,
    area_sqft: 2490,
    location: "Mohali",
    community: "Sector 66A",
    building_name: "Falcon View",
    developer: "Janta Land Promoters Ltd (JLPL)",
    address: "Sector 66A, Mohali",
    latitude: 30.6780,
    longitude: 76.7510,
    furnishing: "semi-furnished",
    description: "JLPL Falcon View is a landmark project offering lavish 3 and 4 BHK apartments. Known for its majestic facade and expansive green areas, the project is a fully integrated township that guarantees a luxurious and secure lifestyle with high-end sports facilities.",
    features: ["Massive Central Green", "Wheelchair friendly", "Gas Pipeline"],
    highlights: ["Developed by highly reputed JLPL", "Close to International Airport", "Excellent resale value"],
    amenities: ["Swimming Pool", "Tennis Court", "Jogging Track", "Clubhouse", "Security"],
    interior_features: ["Wooden Flooring", "Premium UPVC windows", "Acrylic emulsion paint"],
    upcoming_infrastructure: ["Sector 66A Commercial District"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: false
  },
  {
    title: "Hero Homes 2 & 3 BHK Apartments",
    slug: "hero-homes-sector-88-mohali",
    type: "apartment",
    status: "available",
    listing_type: "sale",
    price: 15500000,
    price_currency: "INR",
    bedrooms: 2,
    bedrooms_max: 3,
    bathrooms: 2,
    area_sqft: 1290,
    location: "Mohali",
    community: "Sector 88",
    building_name: "Hero Homes",
    developer: "Hero Realty",
    address: "Sector 88, Mohali",
    latitude: 30.6973,
    longitude: 76.6903,
    furnishing: "semi-furnished",
    description: "Hero Homes Mohali represents a unique concept of sustainable living. With over 25,000 sq ft of clubhouse space and thematic gardens, it is designed to foster a vibrant community life. The apartments are meticulously planned to offer maximum space utility.",
    features: ["IGBC Pre-Gold Certification", "Thematic Gardens", "Smart Space Design"],
    highlights: ["Trusted Hero brand", "Excellent community life", "Affordable luxury"],
    amenities: ["Gym", "Swimming Pool", "Kids Pool", "Jogging Track", "Security"],
    interior_features: ["Vitrified Flooring", "Stainless steel sink", "High-quality CP fittings"],
    upcoming_infrastructure: ["Sector 88 integrated development plan", "New road connectivity to GMADA eco-city"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: false
  },
  {
    title: "Wave Estate Luxury Floors & Apartments",
    slug: "wave-estate-sector-85-mohali",
    type: "apartment",
    status: "available",
    listing_type: "sale",
    price: 21000000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 4,
    bathrooms: 3,
    area_sqft: 1750,
    location: "Mohali",
    community: "Wave Estate",
    building_name: "Wave Estate",
    developer: "Wave Infratech",
    address: "Sector 85, Mohali",
    latitude: 30.6850,
    longitude: 76.7110,
    furnishing: "unfurnished",
    description: "Located in the heart of Mohali, Wave Estate is a gated community offering an array of luxury apartments, independent floors, and villas. It features international standard landscaping, underground cabling, and a serene living environment.",
    features: ["Gated Township", "Underground Electrification", "Wide internal roads"],
    highlights: ["Self-sustained township", "Proximity to Indian School of Business (ISB)", "High security"],
    amenities: ["Garden", "Jogging Track", "Security", "Clubhouse", "Kids Play Area"],
    interior_features: ["Spacious Layouts", "Branded Electricals"],
    upcoming_infrastructure: ["Internal commercial plazas opening soon"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: false
  },
  {
    title: "Escon Primera 3 BHK Luxury Living",
    slug: "escon-primera-airport-road-mohali",
    type: "apartment",
    status: "off-plan",
    listing_type: "sale",
    price: 18500000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 3,
    bathrooms: 3,
    area_sqft: 1550,
    location: "Mohali",
    community: "Airport Road",
    building_name: "Escon Primera",
    developer: "Escon",
    address: "Airport Road, Zirakpur-Mohali Highway",
    latitude: 30.6400,
    longitude: 76.7900,
    furnishing: "semi-furnished",
    description: "Escon Primera brings resort-style living to the Airport Road. Offering smartly designed 3 BHK apartments with dual-aspect ventilation and premium finishes. The project focuses on resort-like amenities and seamless connectivity to the international airport.",
    features: ["Resort Style Architecture", "Cross Ventilation", "Energy Efficient"],
    highlights: ["Direct Airport Road access", "High appreciation corridor", "Boutique development"],
    amenities: ["Pool", "Gym", "Sauna", "Function Room", "Garden"],
    interior_features: ["Premium Wardrobes", "Modular Kitchen", "Designer Bathrooms"],
    upcoming_infrastructure: ["Bharatmala connectivity", "Aerocity extension developments"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: false
  },
  {
    title: "Joy Grand 3 & 4 BHK Luxury Apartments",
    slug: "joy-grand-sector-88-mohali",
    type: "apartment",
    status: "off-plan",
    listing_type: "sale",
    price: 22000000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 4,
    bathrooms: 4,
    area_sqft: 2150,
    location: "Mohali",
    community: "Sector 88",
    building_name: "Joy Grand",
    developer: "Joy Homes",
    address: "Sector 88, Mohali, Punjab",
    latitude: 30.697,
    longitude: 76.69,
    furnishing: "semi-furnished",
    description: "Joy Grand redefines luxury living in Sector 88, a core GMADA sector. Offering expansive 3 and 4 BHK apartments with impeccable design, it features resort-style amenities, sprawling green landscapes, and seamless connectivity to Chandigarh and the International Airport.",
    features: ["Mivan Construction", "Double-Height Lobbies", "Energy Efficient Design"],
    highlights: ["Located in core GMADA Sector 88", "Low-density premium project", "Excellent connectivity"],
    amenities: ["Swimming Pool", "Gym", "Clubhouse", "Kids Play Area", "Jogging Track"],
    interior_features: ["Premium Vitrified Tiles", "Branded CP Fittings", "Modular Kitchen"],
    upcoming_infrastructure: ["Sector 88 commercial development", "Upgraded road networks"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: true
  },
  {
    title: "Homeland Regalia Ultra-Luxury 4 & 5 BHK",
    slug: "homeland-regalia-sector-77-mohali",
    type: "apartment",
    status: "off-plan",
    listing_type: "sale",
    price: 42000000,
    price_currency: "INR",
    bedrooms: 4,
    bedrooms_max: 5,
    bathrooms: 5,
    area_sqft: 3400,
    location: "Mohali",
    community: "Sector 77",
    building_name: "Homeland Regalia",
    developer: "Homeland Group",
    address: "Airport Road, Sector 77, Mohali, Punjab",
    latitude: 30.6865,
    longitude: 76.718,
    furnishing: "semi-furnished",
    description: "Homeland Regalia is the pinnacle of ultra-luxury in Mohali's Sector 77. Designed for the elite, these 4 and 5 BHK residences offer unmatched privacy, towering architecture, and panoramic views of the cityscape. Located directly on the Airport Road, it ensures instant access to Tricity's major hubs.",
    features: ["Smart Home Automation", "Private Elevators", "VRV Air Conditioning"],
    highlights: ["Airport Road frontage", "Exclusive HNI community", "Unobstructed views"],
    amenities: ["Rooftop Infinity Pool", "State-of-the-art Gym", "Concierge Service", "Spa & Salon"],
    interior_features: ["Imported Marble Flooring", "Designer Bathrooms", "Walk-in Closets"],
    upcoming_infrastructure: ["Upcoming commercial high-street", "Airport Road expansion"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: true
  },
  {
    title: "Jubilee EVOQ Premium 3 & 4 BHK Residences",
    slug: "jubilee-evoq-sector-66-mohali",
    type: "apartment",
    status: "off-plan",
    listing_type: "sale",
    price: 35000000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 4,
    bathrooms: 4,
    area_sqft: 2700,
    location: "Mohali",
    community: "Sector 66",
    building_name: "Jubilee EVOQ",
    developer: "Jubilee Group",
    address: "Airport Road, Sector 66, Mohali, Punjab",
    latitude: 30.675,
    longitude: 76.745,
    furnishing: "semi-furnished",
    description: "Jubilee EVOQ presents a limited collection of bespoke 3 and 4 BHK luxury residences on the prestigious Airport Road, Sector 66. Combining avant-garde architecture with world-class lifestyle amenities, EVOQ is designed for the discerning few who seek exclusivity and elegance.",
    features: ["Bespoke Architecture", "Low Density Project", "Grand Drop-off Area"],
    highlights: ["Prime Sector 66 location", "Immediate Airport Road access", "High appreciation potential"],
    amenities: ["Exclusive Clubhouse", "Temperature Controlled Pool", "Squash Court", "Banquet Hall"],
    interior_features: ["Large Balconies", "Premium Wood Finishes", "Advanced Security Systems"],
    upcoming_infrastructure: ["Sector 66 commercial hub", "Enhanced public transport connectivity"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: true
  },
  {
    title: "Emaar The Views 3 & 4 BHK Apartments",
    slug: "emaar-the-views-sector-105-mohali",
    type: "apartment",
    status: "available",
    listing_type: "sale",
    price: 18000000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 4,
    bathrooms: 4,
    area_sqft: 1950,
    location: "Mohali",
    community: "Sector 105",
    building_name: "The Views",
    developer: "Emaar India",
    address: "Mohali Hills, Sector 105, Mohali, Punjab",
    latitude: 30.68,
    longitude: 76.65,
    furnishing: "semi-furnished",
    description: "Part of the expansive Emaar Mohali Hills township, The Views offers premium 3 and 4 BHK apartments surrounded by lush green landscapes. Developed by the globally renowned Emaar Group, this project delivers an international lifestyle, impeccable construction quality, and a thriving community.",
    features: ["Integrated Township Living", "Global Construction Standards", "Extensive Greenery"],
    highlights: ["Emaar brand value", "Ready community infrastructure", "Spacious layouts"],
    amenities: ["Community Center", "Swimming Pool", "Tennis Courts", "Parks & Play Areas"],
    interior_features: ["Vitrified Tiles", "UPVC Windows", "High-quality Sanitaryware"],
    upcoming_infrastructure: ["Improved connectivity to Chandigarh", "Township retail expansion"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: false
  },
  {
    title: "Lutyens by MDB 3 & 4 BHK Luxury Mansions",
    slug: "lutyens-by-mdb-mohali",
    type: "apartment",
    status: "off-plan",
    listing_type: "sale",
    price: 36000000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 4,
    bathrooms: 4,
    area_sqft: 2800,
    location: "Mohali",
    community: "Airport Road",
    building_name: "The Lutyens",
    developer: "MDB Group",
    address: "Airport Road, PR-7, Mohali",
    latitude: 30.655,
    longitude: 76.76,
    furnishing: "semi-furnished",
    description: "Lutyens by MDB brings colonial-era grandeur to Mohali. These opulent 3 and 4 BHK mansions integrate classical architecture with ultra-modern smart technologies. Situated perfectly on the Airport Road (PR-7), the project is an architectural marvel designed to cater to the highest echelons of luxury buyers.",
    features: ["Colonial Architecture", "Private Pools in Select Units", "IGBC Gold Rated"],
    highlights: ["Unmatched colonial luxury", "Direct Airport Road connectivity", "Exclusive low-density towers"],
    amenities: ["Grand Clubhouse", "Infinity Edge Pool", "Cigar Lounge", "Private Theatre", "Concierge"],
    interior_features: ["Italian Marble", "12ft Ceilings", "Smart Climate Control"],
    upcoming_infrastructure: ["Aerocity phase expansions", "New IT corporate parks nearby"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: true
  },
  {
    title: "Ambika La Parisian 3 & 4 BHK French-Style Apartments",
    slug: "ambika-la-parisian-sector-66b-mohali",
    type: "apartment",
    status: "available",
    listing_type: "sale",
    price: 19500000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 4,
    bathrooms: 3,
    area_sqft: 1850,
    location: "Mohali",
    community: "Sector 66B",
    building_name: "La Parisian",
    developer: "Ambika Realcon",
    address: "Sector 66B, IT City, Mohali",
    latitude: 30.669,
    longitude: 76.741,
    furnishing: "semi-furnished",
    description: "Ambika La Parisian is a Parisian-themed luxury residential project in Sector 66B. Designed to mimic European aesthetics, the project offers ample open spaces, exquisite landscaping, and modern 3 and 4 BHK layouts. It provides excellent ROI potential due to its proximity to the IT hub.",
    features: ["Parisian Themed Architecture", "Lush Landscaped Gardens", "Excellent Cross Ventilation"],
    highlights: ["Close to Infosys and IT City", "Unique architectural theme", "Ready to move in options"],
    amenities: ["Parisian Cafe", "Swimming Pool", "Gymnasium", "Kids Play Area"],
    interior_features: ["Wooden Flooring in Master Bed", "Modular Kitchen", "Large Balconies"],
    upcoming_infrastructure: ["IT City expansion", "Commercial zones in Sector 66"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: false
  },
  {
    title: "Central Town Premium 3 BHK Apartments",
    slug: "central-town-sector-115-mohali",
    type: "apartment",
    status: "available",
    listing_type: "sale",
    price: 9500000,
    price_currency: "INR",
    bedrooms: 3,
    bedrooms_max: 3,
    bathrooms: 3,
    area_sqft: 1450,
    location: "Mohali",
    community: "Sector 115",
    building_name: "Central Town",
    developer: "Central Town Developers",
    address: "Sector 115, Kharar-Landran Road, Mohali",
    latitude: 30.725,
    longitude: 76.65,
    furnishing: "unfurnished",
    description: "Central Town offers an excellent entry into Mohali's property market with highly functional 3 BHK apartments. Located off the Kharar-Landran highway, it balances peaceful community living with excellent access to educational institutions and commercial centers.",
    features: ["Gated Community", "Stilt Parking", "Earthquake Resistant"],
    highlights: ["Value for money", "Close to educational hubs", "Established neighborhood"],
    amenities: ["Park", "Jogging Track", "24/7 Security", "Clubhouse"],
    interior_features: ["Vitrified Tiles", "Spacious Layout", "Branded Fittings"],
    upcoming_infrastructure: ["Highway expansion", "New retail outlets on Kharar Road"],
    images: getRandomImages(),
    agent_name: "Amritpal Singh",
    agent_phone: "+91 7814613916",
    agent_email: "hello@realtyconsultants.in",
    featured: false
  }
];

function escapeCSV(val) {
  if (val === null || val === undefined) return '';
  if (Array.isArray(val)) {
    // Format array for postgres: {"A","B"}
    const arrStr = val.map(item => '"' + item.replace(/"/g, '""') + '"').join(',');
    const pgArray = '{' + arrStr + '}';
    // Now escape the pgArray for CSV
    return '"' + pgArray.replace(/"/g, '""') + '"';
  }
  if (typeof val === 'string') {
    return '"' + val.replace(/"/g, '""') + '"';
  }
  return val;
}

const header = Object.keys(projects[0]).join(',');
const rows = projects.map(p => {
  return Object.values(p).map(escapeCSV).join(',');
});

// We must join with '\n' to put each object on a new row!
fs.writeFileSync('C:/Users/Magicbook/Desktop/Realty Holding and Management Consultants/mohali_luxury_apartments.csv', [header, ...rows].join('\n'), 'utf8');
console.log('Done!');
