import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || "";
const supabase = createClient(supabaseUrl, serviceKey, { auth: { persistSession: false } });

const seoData = [
  {
    slug: "wellington-heights",
    og_title: "Wellington Heights Mohali | 2/3/4 BHK, Sector 117",
    og_description: "TDI Wellington Heights — ready-to-move 2/3/4 BHK in Sector 117 Mohali on 200ft Airport Road. ISO 9001:2008 certified developer. Prices from ₹1.09 Cr.",
    description: `Wellington Heights is one of the most established ready-to-move addresses in the TDI City township at Sector 117, Mohali. Developed by TDI Infratech — an ISO 9001:2008 certified developer with over two decades of delivery track record — the project sits directly on the 200ft Airport Road (NH-5) and offers 2, 3, and 4 BHK apartments across 14 towers.\n\nThe society is part of TDI City, a self-contained township that already includes a retail spine, schools, and healthcare nearby. Resale prices have been rising steadily: average asking price moved from ₹6,350 to ₹6,800 per sq. ft. in Q1 2026 alone — a 7% quarterly jump — which reflects real demand, not promotional pricing. VR Punjab Mall and TDI Park Street Mall are within 3 km. Max Super Speciality Hospital is within 7 km. Kharar Railway Station is 6 km away.\n\nFor buyers evaluating finished, occupied societies where you can see exactly what you are getting before you commit, Wellington Heights remains one of the few genuinely ready-to-move options in the Sector 117 corridor at this price point.`,
    upcoming_infrastructure: [
      "Airport Road (NH-5) Corridor Upgrade: NH-5 passing Sector 117 is seeing increased service lane development to manage traffic from the Kharar-Mohali growth corridor. This directly benefits Wellington Heights' front access.",
      "North Country Mall Expansion Zone: The 22-acre North Country Mall adjacent to TDI City continues to attract anchor tenants. Retail growth in this cluster is expected to push residential rental demand higher in 2026-27.",
      "Chandigarh-Kharar Road Infrastructure: State Highway 12A improvements under Mohali Smart City plans include signal-free stretches between Kharar and Sector 117, reducing daily commute times for residents.",
      "Kharar Railway Station Upgrade: RRTS proposals for the Chandigarh-Mohali-Kharar corridor, if approved, would make the 6km proximity to Kharar Station a significant daily commute asset."
    ],
    faqs: [
      { question: "Prices rose 7% in Q1 2026 alone. Is Wellington Heights overpriced now?", answer: "Not necessarily. The ₹6,800/sqft rate still sits slightly above the Sector 117 average of ₹6,700/sqft — not dramatically so. For a ready-to-move, ISO-certified project in an established township with confirmed occupancy, this premium is justified. The concern is: if you are buying for short-term resale, secondary market liquidity is moderate here, not exceptional. For end-users and long-term holders, the price trajectory is positive." },
      { question: "Is TDI Infratech financially stable enough to guarantee services in an already-delivered project?", answer: "TDI has faced financial headwinds in other markets but Wellington Heights is already delivered, occupied, and managed by a resident welfare association. The buyer's risk here is not construction-related — it is the ongoing maintenance quality. On-ground reviews describe maintenance as adequate, though not luxury-grade. Verify the maintenance fund balance before buying in resale." },
      { question: "Is Sector 117 prone to waterlogging during monsoon?", answer: "This has been a historically valid concern for parts of the sector. Wellington Heights II (newer F Towers) has improved drainage and basement sealing based on field feedback. Buyers should inspect lower-floor units and parking areas during or just after the monsoon before finalising." },
      { question: "Is this a good rental investment given the proximity to IT hubs?", answer: "Yes — with conditions. Infosys and HDFC's Sector 66 campus belts are within 2-5 km. The 3 BHK units consistently generate rental yields in the ₹18,000-25,000 per month range. However, there is significant rental supply in the corridor, so vacancy periods between tenants can run 4-8 weeks. Net yields are solid but not exceptional." }
    ]
  },
  {
    slug: "evoq-antalia",
    og_title: "Evoq Antalia Mohali | Ultra-Luxury 3/4/5 BHK Sector 66",
    og_description: "Evoq Antalia — only 180 apartments on 4.4 acres in Sector 66 Mohali. 7-star Novotel-managed clubhouse. Rooftop infinity pool. From ₹4.37 Cr. RERA approved.",
    description: `Evoq Antalia is positioned as one of the most exclusive residential developments in the Tricity region. With just 180 apartments spread across 4.4 acres and four towers in Sector 66, this is a genuinely low-density project at a time when most Mohali launches pack 800+ units onto similar land areas.\n\nThe project's standout claim is its 50,000 sq. ft. clubhouse — managed by Novotel Hotel, not the builder or an RWA. This is the first time a hotel brand has taken on clubhouse management in a residential project in this part of Punjab. For residents, it means professionally trained staff, standardised service delivery, and hotel-grade F&B within the society.\n\nEvery floor has only two apartments. Each unit comes standard with VRV air conditioning, Italian marble flooring, and 3-side open layouts with 5 private lifts per tower — one of which opens directly into the home. The project has 86% open green area and is the first in Mohali to be awarded for extensive green landscaping. Brand Ambassador Hrithik Roshan is associated with the brand, which has driven strong visibility and a waitlist-style booking process.\n\nRERA completion is September 2030. This is a long timeline. Buyers should price this in — the world will look different in 2030 — but the location on Airport Road Sector 66 has proven decade-long appreciation and the density advantage compounds over time.`,
    upcoming_infrastructure: [
      "IT City Sector 66 Expansion: Infosys, Tech Mahindra, and other anchor tenants continue to expand their Sector 66-66A footprint. As corporate campuses grow, executive demand for nearby luxury residential inventory will intensify — directly benefiting Antalia's tenant and buyer profile.",
      "Aerocity Commercial Growth: GMADA Aerocity, 8 minutes away, is adding retail, hospitality, and commercial space through 2026-28. This creates a catchment of high-income professionals who will lease in Antalia.",
      "Chandigarh Airport Expansion: The International Airport's terminal upgrade and increased domestic/international routes will raise long-term demand from NRI buyers and frequent flyers — exactly Antalia's target buyer.",
      "PR-7 Expressway Service Development: Planned widening of service lanes on Airport Road from CP67 to Sector 77 will improve peak-hour traffic movement in front of the Antalia site."
    ],
    faqs: [
      { question: "Evoq Realtech is a relatively new developer. What is their track record?", answer: "Evoq Realtech is led by Gaurav Goyal and Satish Katyal, both with prior experience in commercial real estate in Mohali. Antalia is their flagship residential project. They do not yet have a delivered residential project of this scale, which is a genuine risk factor buyers should acknowledge. RERA registration and a Novotel management tie-up add credibility, but this is a developer debut at this price point. Visit the site, verify construction pace, and ask for structural completion milestones before committing." },
      { question: "With only 180 units, is exit liquidity a problem?", answer: "The limited supply cuts both ways. Fewer units means less resale competition when you exit — but it also means a thinner resale market. The best exit strategy for Antalia buyers is a 5-7 year hold after possession, by which time the Novotel association and mature community will justify premium resale pricing. Short-term flipping before possession carries execution risk given the 2030 timeline." },
      { question: "Does the Novotel management agreement have a fixed term?", answer: "The management arrangement is part of the project's core positioning. Buyers should request a copy of the agreement with Novotel and verify the term length and renewal conditions before purchase. If Novotel exits post-possession, the lifestyle differentiator disappears." },
      { question: "How does it compare to Noble Callista, which is similarly positioned in the same sector?", answer: "Antalia is more exclusive (180 units vs 400 at Callista) and has hotel-managed amenities — but its RERA deadline is 3 years later (2030 vs 2027). Callista is a better short-term delivery bet. Antalia is a better long-term lifestyle play if you can wait and trust the developer." }
    ]
  },
  {
    slug: "jubilee-city-gardens",
    og_title: "Jubilee City Gardens Mohali | Plots & 3BHK, Sector 116",
    og_description: "Jubilee City Gardens — 25-acre RERA-registered township in Sector 116 Mohali. Freehold plots from 90-150 sq. yards. 3 BHK flats & builder floors. PR-6 road.",
    description: `Jubilee City Gardens is one of the very few RERA-registered, gated, freehold plot developments in Mohali — and in early 2025, it became ready to move. The township covers 25 acres in Sector 116 on the Kharar-Landran Road, and its biggest long-term asset is its position: it sits directly on the upcoming 200ft PR-6 road that will connect the Landran-Banur highway to Airport Road (PR-7).\n\nThis is not a luxury high-rise play. It is a land ownership story. Buyers get freehold plots between 90 and 150 sq. yards, with 30ft internal roads, underground electricity, a sewerage treatment plant, 24/7 gated security, and GMADA-approved infrastructure. A 3 BHK apartment and builder floor option is also available for buyers who don't want to self-construct.\n\nPlot prices currently run ₹75 lakh to ₹1.17 crore depending on size, facing, and road proximity. Early investors in PR-6 corridor land have seen values move meaningfully since 2022. The developer, Jubilee Group, has successfully delivered Jubilee Square, Jubilee Walk, and other projects in Mohali — this is not a first-time developer.\n\nFor buyers who want land ownership rather than an apartment, and who understand that Sector 116 is still a developing market rather than a prime one, Jubilee City Gardens is one of the better-structured options available in this price range.`,
    upcoming_infrastructure: [
      "PR-6 Road (200ft GMADA Road): The upcoming 200ft PR-6 road passes directly through the Jubilee City Gardens site boundary. Once complete, this road connects Kharar-Landran highway to Airport Road (PR-7) — cutting cross-sector travel time significantly. This is the single biggest value trigger for this project.",
      "Sector 116 Residential Densification: With 9 projects now in Sector 116, the social infrastructure — schools, clinics, daily retail — is developing organically. DPS Mohali and Chandigarh Group of Colleges are within 5-10 minutes.",
      "Landran-Banur Industrial Belt Growth: The Landran corridor is seeing warehouse and light industrial development, increasing working population in the catchment and supporting long-term rental demand.",
      "Airport Road (PR-7) Link: As PR-6 bridges the gap between Kharar and Airport Road, Jubilee's Sector 116 position shifts from peripheral to genuinely connected — a trajectory that typically accelerates price appreciation."
    ],
    faqs: [
      { question: "Sector 116 is 20 km from the airport. Why should I invest here instead of a closer sector?", answer: "Two reasons. First, price: plots near the airport corridor (Sector 77, 83A) cost 2-3x more per square yard. Second, timing: PR-6 road completion will structurally compress the distance advantage that premium sectors enjoy today. Sector 116 is a patient capital play — correct for someone with a 5-10 year hold horizon, not for someone seeking quick appreciation." },
      { question: "As a freehold plot buyer, what exactly do I own?", answer: "You own the land outright under your name — registered in your favour. There is no cooperative society structure or allotment-based ownership. GMADA-approved infrastructure means the roads and utilities are developed to civic standards, not builder-grade. The RERA number PBRERA-SAS81-PR0795 covers this specific township and can be verified on the Punjab RERA portal." },
      { question: "Can I build a house immediately after purchase?", answer: "Yes. The project has been ready since March 2025. Boundary walls, street lighting, security, and underground utilities are operational. Some buyers have already commenced construction. The internal roads are 30ft wide, allowing construction vehicles easy access." },
      { question: "How is the monsoon drainage in Sector 116?", answer: "Unlike some older Mohali sectors that developed organically, Jubilee City Gardens includes a dedicated sewerage treatment plant and planned storm-water channels. Field reviews confirm the internal roads handle heavy rain better than unplanned colonies in the vicinity. However, the external PR-6 road stretch remains partially under development, which can cause seasonal inconvenience at the project entry." }
    ]
  },
  {
    slug: "horizon-belmond",
    og_title: "Horizon Belmond Mohali | 3+1/4+1 BHK, Sector 88 Mohali",
    og_description: "Horizon Belmond — designed by Sussanne Khan, only 340 units in 12.54 acres, Sector 88 Mohali. 78% open area, 25,000 sq.ft. Club Stardom. Possession March 2027.",
    description: `Horizon Belmond is the only residential project in Punjab to carry the design signature of Sussanne Khan — India's most prominent interior design name, known for The Charcoal Project and landmark luxury residences in Mumbai. Her involvement here is not a logo placement. The apartment interiors, material palette, and spatial language reflect her studio's characteristic contrast of bold geometry with warm textures.\n\nThe project occupies 12.54 acres in Sector 88 on a 3-side open site — one of the rarest configurations in GMADA's land bank. Thirty-floor towers house only 340 apartments, giving each resident genuine breathing room. Two apartments per floor means no crowded corridors, no elevator wait, and no community of strangers outside your door.\n\nThe 78% open green area, combined with 25,000 sq. ft. Club Stardom, is not marketing language — it is verifiable: 12.54 acres with 340 units mathematically cannot be dense. Possession is RERA-scheduled for March 2027, with Tata Capital loan approval already in place. The project has delivered 2 apartments per floor across six towers with panoramic views on multiple sides.\n\nFor buyers who care about who designed their home — not just who built it — Horizon Belmond is the only answer in Mohali.`,
    upcoming_infrastructure: [
      "Sector 88 Growth Corridor: Sector 88 sits at the junction of Airport Road and the Mohali Railway Station corridor. Multiple premium projects — Hero Homes, Joy Grand, and Belmond itself — have established the sector as a luxury residential zone, attracting social infrastructure investment like schools and clinics in their wake.",
      "Mohali Railway Station Connectivity: The station, 10 minutes from Belmond, is undergoing platform capacity expansion as part of railway board capital expenditure. Proposed metro links in GMADA's long-term plan include a station in this corridor.",
      "Airport Road Commercial Expansion: Hotels, serviced apartments, and retail are being developed along the 200ft Airport Road stretch near Sector 88-89. This reduces the \"underdeveloped\" perception of the sector and raises asset prices.",
      "ISB / IT City Proximity Benefit: As the Indian School of Business and IT City employers expand hiring, demand for premium residential within 10 minutes of campus is rising. Belmond sits in this radius."
    ],
    faqs: [
      { question: "The FAQ section was empty on this listing — what should buyers actually know before investing?", answer: "Three things. First, possession is March 2027 — verify construction progress on your site visit; the structure should be significantly advanced by now. Second, Horizon Group Punjab has delivered prior projects in Mohali but not at this price point — this is their premium launch. Third, maintenance costs for a Sussanne Khan-designed society will not be cheap. Budget ₹5-7 per sq. ft. per month given the premium clubhouse and landscaping maintenance." },
      { question: "Are the Horizon Kohinoor duplexes (5 BHK) the same RERA registration as the main project?", answer: "Yes. The Kohinoor segment (5 BHK + duplex) is part of the same PBRERA-SAS81-PR0813 registration. These are premium-priced units within the same tower complex — not a separate project. Buyers interested in the duplex tier should confirm the specific tower allocation and floor range." },
      { question: "With only 2 apartments per floor, is this truly private?", answer: "By Mohali high-rise standards, yes. Two units per floor with a dedicated elevator means your floor corridor has exactly one neighbour. Compare this to typical projects with 4-6 units per floor sharing two lifts. The trade-off: building maintenance costs are distributed across fewer units, making per-unit maintenance charges higher." },
      { question: "The design pedigree is strong — but how does construction quality compare?", answer: "Mivan (aluminium formwork) construction is used, which is industry-best for concrete wall quality and dimensional accuracy. Tata Capital's project approval is also a quality signal — banks conduct independent technical due diligence before lending. On-ground, the project is described as progressing well on structure. Finish-level quality will be visible only at handover." }
    ]
  },
  {
    slug: "hero-homes",
    og_title: "Hero Homes Mohali | 2/3/4 BHK by Hero Group, Sector 88",
    og_description: "Hero Homes Sector 88 Mohali — by the USD 5 billion Hero Group. IGBC Gold certified. 18.49 acres, 14 towers. 87% open space. Prices from ₹1.11 Cr. Phase 1 ready.",
    description: `Hero Homes brings an unusual proposition to Mohali's luxury segment: a project built around sustainability and community as a core delivery, not an afterthought. The developer is Hero Realty — the real estate arm of the Hero Group, a USD 5 billion enterprise — and the brand's credibility is reflected in both the construction standards and the post-possession management.\n\nThe project spans 18.49 acres in central Sector 88 with 14 towers of 25 floors and 1,286 apartments. 87% of the site is open space. The 25,000 sq. ft. club is functional, not aspirational. The project has received IGBC Pre-certification Gold Rating for its sustainable design — solar panels, 100% rainwater harvesting, and grey water recycling for gardening and flushing are built into the structure, not offered as premium upgrades.\n\nPrices have appreciated 50%+ from launch for Phase 1 buyers. Current secondary market pricing sits at ₹9,400/sqft as of Q1 2026 — a 3.87% quarterly rise. Some towers are ready and families are in residence. For buyers who want a large-format, delivered project with a trusted brand, institutional-grade RERA compliance, and a genuine green ethos, Hero Homes is the most credible offering in the Sector 88 belt.`,
    upcoming_infrastructure: [
      "Proposed Metro Corridor: Hero Homes Sector 88 is located near the proposed metro corridor identified in Mohali's transport masterplan. If the metro route is confirmed, the nearest station would be within 10-15 minutes — a significant commute value driver.",
      "Judicial and Administrative Complex Growth: The project is adjacent to the Mohali Judicial Complex and District Administrative Complex. These institutions attract salaried professionals who are stable, high-quality residential tenants — underpinning rental yields.",
      "Sector 88 Smart Infrastructure: GMADA's planned smart infrastructure upgrade for Sector 88 includes dedicated 66KV sub-stations and advanced storm-water drainage — addressing the monsoon concern that affects several Mohali sectors.",
      "IT City Expansion via Airport Road: As IT City (10 minutes away) adds corporate campuses, the catchment for mid-to-premium residential in Sector 88 expands. Hero Homes' price point sits in the sweet spot for IT professionals who want quality but cannot yet afford Sector 66's ultra-luxury pricing."
    ],
    faqs: [
      { question: "Phase 1 is ready. What is the status of the remaining towers?", answer: "The project has three phases. Phase 1 towers are delivered and occupied. Phase 2 and 3 towers are under construction with staggered handovers ongoing through 2025-2026. The RERA completion date is June-July 2025 for the overall project, with phased delivery underway. Visit the site to see which specific tower is ready before purchasing." },
      { question: "Is Hero Homes genuinely IGBC certified or is it just a marketing claim?", answer: "The IGBC Pre-certification Gold rating is a third-party assessment by the Indian Green Building Council. It is awarded before completion based on design intent and systems installed. Post-completion performance depends on actual operation of the solar panels, rainwater systems, and waste management. On-ground residents confirm the no-vehicle ground level is strictly enforced, which is an operational green standard. The rating is legitimate." },
      { question: "Prices have risen 50% from launch. Is there still appreciation potential?", answer: "At ₹9,400/sqft, Hero Homes is priced at or above the Sector 88 market average. The primary appreciation case now rests on: the proposed metro connectivity, continued IT City expansion, and the Hero brand's ability to hold pricing above generic projects. Short-term appreciation from here is moderate. Long-term (5+ years), the fundamentals support continued growth." },
      { question: "Can I get a home loan on a Hero Homes unit?", answer: "Yes. The project has bank loan approvals from multiple lenders. Given Hero Group's corporate standing, financing is straightforward. SBI, HDFC, and private banks have active tie-ups." }
    ]
  },
  {
    slug: "beverly-golf-hills",
    og_title: "Beverly Golf Hills Mohali | 3/4 BHK + Golf Range, Sector 65",
    og_description: "Beverly Golf Hills — 424 Vastu-compliant 3/4 BHK apartments in Sector 65, 0 km from Chandigarh. Complimentary 10-acre golf range membership. Ready to move.",
    description: `Beverly Golf Hills occupies one of the most distinctive positions in Mohali's residential market: it is the only apartment complex in the Tricity where residents receive complimentary lifetime membership to a dedicated 10+ acre golf range. This is not a shared public course — it is an exclusive range within the project's grounds, ensuring it will never be blocked by future construction.\n\nThe project is ready to move, with over 100 families already in residence as of 2026. It sits on 7.12 acres in Sector 65, directly adjoining Chandigarh — putting it 0 km from the city boundary and within 8.5 km of the international airport. Current secondary market pricing is approximately ₹9,800/sqft, with rental income running ₹67,500 to ₹1 lakh per month for 3-4 BHK units.\n\nApartments are fully air-conditioned, Vastu-compliant, and come with Italian marble lobby, Smart Home Access Control, and a mini theatre within the clubhouse. The building uses high-grade UPVC windows with toughened acoustic glass — a specific investment in noise isolation that matters given the proximity to the cricket stadium area.\n\nThis is not a project for buyers seeking the newest launch. It is for buyers who want a mature, occupied community in a premium location, with a unique lifestyle amenity that no competitor can replicate.`,
    upcoming_infrastructure: [
      "Sector 65 Market Stability: Sector 65 is one of Mohali's established premium sectors with no available undeveloped land. This scarcity means no new competing inventory will enter the area, protecting asset values from supply-side pressure.",
      "CP67 and Phase 7 Retail Growth: CP67 Mall (10 min) and the Phase 7 commercial strip continue to expand, with new F&B and lifestyle brands opening. This ongoing retail maturation adds to the quality-of-life premium that Sector 65 commands.",
      "Fortis Hospital Expansion: Fortis Mohali (4.5 km) is among India's leading private hospitals. Its presence and any expansion plans in the sector directly benefit residential property values in its immediate radius.",
      "Chandigarh City-Core Connectivity: Sector 65's position at the Chandigarh border means that any upgrades to inner-city roads (Madhya Marg or Dakshin Marg connections) automatically improve Beverly Golf Hills' commute access to Sector 17, the High Court, and commercial districts."
    ],
    faqs: [
      { question: "Is the golf range truly exclusive or is it open to the public?", answer: "It is a complimentary membership for residents — not a public facility. The 10+ acre range is part of the project's permanent landscape, protected from future construction by its sheer size and integration into the master plan. Residents have reported consistent access and maintenance as of 2026." },
      { question: "With 100+ families already in residence, how is the society management functioning?", answer: "Reviews describe maintenance as professional and the community as active. The high occupancy rate (100+ families in 424 units) ensures maintenance costs are spread across a significant base, keeping per-unit costs manageable. This is a key reason to prefer occupied societies: maintenance funds are operational, not theoretical." },
      { question: "The starting price of ₹3.39 Cr feels steep for Sector 65. Is it justified?", answer: "The ₹9,800/sqft rate reflects the 0-km-from-Chandigarh location, ready-to-move status, golf range exclusivity, and fully air-conditioned units. Comparable fully AC ready-to-move apartments in Sector 65 do not exist at lower prices — this is the only such project in the sector. Whether the price is justified depends on your use case: end-users who value the lifestyle premium will find it fair. Pure investors calculating yield will find the cap rate modest." },
      { question: "Are there any pending legal issues with the project?", answer: "The project carries two RERA registrations (PR0111 and PR0451), both from PBRERA-SAS81. No consumer commission disputes or pending litigation has been publicly documented for this project. Always verify on the Punjab RERA portal before transacting." }
    ]
  },
  {
    slug: "ambika-la-parisian",
    og_title: "Ambika La Parisian Mohali | 2/3/4 BHK Sector 66B IT City",
    og_description: "Ambika La Parisian — European-themed ready-to-move 2/3/4 BHK in Sector 66B Mohali. 70% open area, near ISB and Airport. Mivan construction. From ₹1.20 Cr.",
    description: `Ambika La Parisian is the Tricity's only residential project built around a Parisian design philosophy — French architectural facades, fountain courtyards, flower bed landscaping, and a colour scheme drawn from European city centres. The result is a visual identity that is instantly distinctive in a market where most towers look identical.\n\nThe project spans 6.92 acres in Sector 66-B (IT City), with nine 15-floor towers housing 576 apartments in 2, 3, and 4 BHK configurations. Phase 1 is fully operational and occupied. Phase 2 (Towers 1-5) is now ready to move. The project sits 500-700 metres from Airport Road and within 10 minutes of Chandigarh International Airport, ISB, and IISER.\n\nConstruction uses Mivan (aluminium formwork) RCC framing — earthquake resistant and dimensionally precise. PNB Housing Finance has approved the project for loans. Home loan approvals are available from HDFC, PNB, SBI, and ICICI.\n\nOne issue buyers should be aware of: Phase 1 faced consumer commission complaints about construction defects — a matter of public record. The developer was held accountable and rectification was ordered. Phase 2 units are being marketed with enhanced quality checks and corrected carpet area calculations. Buyers purchasing Phase 2 should inspect the sample flat carefully and compare delivered specifications against the buyer agreement.`,
    upcoming_infrastructure: [
      "IT City Commercial Expansion: Ambika La Parisian is 800m from IT City Mohali's main entrance. As IT companies expand campuses in Sectors 66-68, the residential catchment immediately around La Parisian benefits from a growing pool of working professionals seeking quality housing near their office.",
      "Aerocity Growth: GMADA Aerocity's hotel and retail component is under active development 10 minutes away. This will elevate the surrounding residential premium as Aerocity matures into a commercial destination.",
      "Airport Road Demand Corridor: The 200ft Airport Road corridor from CP67 to Sector 77 is seeing hotel, serviced apartment, and premium retail entry. This infrastructure investment lifts land value across all projects on or adjacent to this road.",
      "Sector 66B Social Infrastructure: Manav Rachna International School and several healthcare facilities are within 8 minutes. As Sector 66B fills up with delivered projects like Ambika and Noble Callista, demand for local schools, clinics, and daily retail will prompt new supply — further improving the neighbourhood score."
    ],
    faqs: [
      { question: "Phase 1 had documented construction defect complaints. Should I avoid the project entirely?", answer: "Not necessarily. Consumer commission complaints are not uncommon for large-scale projects. The relevant question is whether the defects were systemic or isolated, and whether the developer complied with the commission's orders. Field reports suggest compliance was partial but eventual. Phase 2, being constructed later, benefits from corrected processes. Engage a structural engineer for a pre-possession inspection — this is money well spent on any project where Phase 1 had issues." },
      { question: "How does La Parisian compare to Noble Callista in the same sector?", answer: "Noble Callista is larger (400 units vs 576), newer (RERA 2027), more expensive (from ₹2.35 Cr vs ₹1.20 Cr), and targets a different buyer. La Parisian is ready, occupied, and affordable. If you need a working, liveable community now, La Parisian is the practical choice. If you want the premium version and can wait until 2027, Callista is the upgrade." },
      { question: "What are current resale prices for Phase 2 units?", answer: "Resale 3 BHK units are currently quoted at ₹1.55 Cr to ₹1.70 Cr as of late 2025. This is within striking distance of the developer's primary prices, meaning there is not yet a major resale premium — but the ready-to-move status means no construction risk for the buyer, which justifies the marginal premium over under-construction options." },
      { question: "Is the Parisian theme maintained in the common areas or just the branding?", answer: "The fountains, flower bed landscaping, French window designs, and courtyard layout are genuinely part of the construction — not just marketing renders. Residents consistently mention the aesthetic as the top reason they chose La Parisian over functionally similar projects. The theme is maintained in Phase 1 common areas as of 2026 field visits." }
    ]
  },
  {
    slug: "noble-callista",
    og_title: "Noble Callista Mohali | 3.5/4.5/5.5 BHK, Sector 66B IT City",
    og_description: "Noble Callista — 400 ultra-luxury apartments, 3-side open site, Sector 66B Mohali. 5 clubs, 40,000 sq.ft. master clubhouse, individual lift per flat. From ₹2.35 Cr.",
    description: `Noble Callista claims the rarest land configuration in Mohali's IT City: a 3-side open site in Sector 66B. In a belt where most projects share boundaries on all sides, this means unobstructed views and natural light from three directions for the majority of units.\n\nOnly 400 apartments are planned across 6.84 acres and four towers — a density that works out to fewer than 60 units per acre. Compare this to the Sector 66B average, which often runs 100+ units per acre. The low density is the project's core proposition: residents of Noble Callista will never encounter the overcrowded gym, overloaded pool, or elevator wait time that plagues high-occupancy projects.\n\nThe amenity structure is genuinely differentiated: 5 clubs (4 mini tower-level clubs plus a 40,000 sq. ft. master clubhouse), a half-Olympic all-weather swimming pool, a separate private pool for women, and an individual dedicated lift per apartment. The last feature is almost unheard of in Mohali — and it eliminates the shared elevator corridor experience entirely.\n\nAll homes are centrally air-conditioned. Mivan construction (aluminium formwork) is used throughout. A World Top-100 Architect (name not publicly disclosed by the developer) is credited with the design. Sanitary fittings are Jacuzzi, Kohler, or Grohe — or equivalent. RERA possession: March 2027.`,
    upcoming_infrastructure: [
      "IT City Sector 66 Corporate Growth: Noble Callista's 3-side open corner position in Sector 66B means its immediate surroundings are sector-dividing roads on two sides — a protected buffer that will remain clear even as the area densifies. IT City expansion will increase the professional population within walking distance.",
      "Airport Road Commercial Growth: The 200ft Airport Road, 200m from the project, is seeing premium hotel and retail development through 2025-28. Residents will benefit from improved food, services, and nightlife options within a 5-minute drive.",
      "Aerocity Expansion: GMADA Aerocity's Phase 2 development is ongoing 10 minutes from Callista. As Aerocity matures, the Sector 66B belt between IT City and Aerocity becomes a prime address for executives working in either cluster.",
      "Mohali Railway Station Link: With enhanced connectivity to the railway station (1.58 km via direct roads), residents have access to Chandigarh city and intercity rail without Airport Road congestion."
    ],
    faqs: [
      { question: "With March 2027 possession, is construction on track?", answer: "As of early 2026, the project is described as \"near possession\" on developer channels. RERA registration PBRERA-SAS81-PR0748 can be verified on the Punjab RERA portal for construction stage milestones. Sector 66B ranks in the Top 30 Mohali localities — social infrastructure is already in place, reducing the \"undeveloped surroundings\" risk that plagues newer sectors." },
      { question: "Individual lifts per apartment — what does that actually mean operationally?", answer: "Each apartment has its own dedicated lift shaft. When you call the elevator, only your unit can summon it — no waiting for neighbours, no strangers in your lift lobby. This is a genuine privacy and convenience differentiator, not a marketing phrase. The maintenance cost implication: more lifts mean higher AMC (annual maintenance contract) charges — build this into your monthly cost calculations." },
      { question: "Is the 40,000 sq. ft. master clubhouse proportional for only 400 units?", answer: "By any measure, yes. That is 100 sq. ft. of clubhouse per apartment — a ratio you will struggle to find anywhere in Tricity. Compare this to projects with 800+ units sharing a 25,000 sq. ft. club, where per-member floor space is under 30 sq. ft. Noble Callista's clubhouse will not feel crowded even at full occupancy." },
      { question: "How is the resale market for this sector?", answer: "Sector 66B is rated a luxury locality (Top 26 in Mohali per 99acres data). Resale for under-construction premium projects in this belt has been active, driven by IT professionals upgrading from older societies. After possession in March 2027, the combination of low density, superior amenities, and prime location should support strong secondary pricing." }
    ]
  },
  {
    slug: "marbella-royce",
    og_title: "Marbella Royce Mohali | 4/5 BHK Tallest Tower, Sector 83A",
    og_description: "Marbella Royce — Mohali's tallest residential skyscraper at 42 floors. 4/5 BHK from ₹3.12 Cr in Sector 83A IT City. IGBC certified. RERA: Dec 2030.",
    description: `Marbella Royce is the tallest residential tower in Mohali — 42 floors, confirmed by RERA registration PBRERA-SAS81-PRO889 and the developer's own documentation. Note: some earlier descriptions of the project quoted 33 floors — this is incorrect. The approved and under-construction project is 42 storeys. Buyers should verify this on the RERA portal.\n\nSituated on 8.01 acres at GHS Site No. 7, Sector 83A, directly on the 200ft IT City Road — adjacent to Infosys and Plaksha University — Marbella Royce is designed by Ar. Tripat Girdhar with interiors by Ar. Zafar Choudhary and landscaping by Oracles. The project is IGBC green building certified, with 53 amenities and a 50,000 sq. ft. clubhouse.\n\nUnit sizes are large: 4 BHK starts at 3,120 sq. ft. (corner units at 3,300 sq. ft.) and 5 BHK starts at 4,123 sq. ft. (corner at 4,300 sq. ft.). Prices start at ₹3.12 Cr for 4 BHK and ₹4.12 Cr for 5 BHK. Higher floors and corner units command an additional ₹10-20 lakh premium. Construction uses Mivan Malaysian technology, described as earthquake resistant.\n\nThe building includes pre-installed conduits for home automation, digital door locks, VRV-ready zones for air conditioning, and high-speed fiber infrastructure. Home loans are approved through SBI, HDFC, and PNB at 80% LTV.\n\nRERA possession is December 2030 — a long timeline. For buyers committing now, this is a 4-5 year construction journey. The upside: the Tricity's first 42-floor residential skyline position, combined with a maturing IT City location, creates a genuinely differentiated asset class.`,
    upcoming_infrastructure: [
      "IT City Sector 83A Anchor Tenant Growth: Infosys campus is directly adjacent. Plaksha University and ISB are within 10 minutes. As these institutions grow, the demand for executive housing within walking or cycling distance of their gates will intensify — exactly what Royce offers.",
      "Knowledge Hub Expansion: Plans for additional institutional development (tech campuses and university expansions) along the IT City corridor are in GMADA's forward plan. Sector 83A's position at this intersection will compound over the project's 2030 delivery timeline.",
      "Airport Road Widening and Service Lane Development: PR-7 Airport Road's 200ft corridor in front of Royce is seeing structured service lane development to handle the luxury high-rise belt's traffic. This will address peak-hour bottlenecks by delivery time.",
      "Premium Retail Catchment: Major retail developers have acquired land in the Sector 83A-84 belt. By 2028-30, residents of Royce will have premium grocery, F&B, and lifestyle retail within 5 minutes — a gap that currently exists in this location."
    ],
    faqs: [
      { question: "Why does the project page say 33 floors when the RERA says 42 floors?", answer: "The earlier description on the listing page was incorrect. The correct height is 42 storeys, per the official Marbella Royce developer website, RERA registration documents, and multiple property platforms. This discrepancy has been flagged and should be corrected. Always verify project height on the Punjab RERA portal (PBRERA-SAS81-PRO889)." },
      { question: "Possession is December 2030. What happens if the developer delays?", answer: "Under RERA Punjab, buyers are entitled to interest on amounts paid (at the SBI MCLR rate) for each month of delay beyond the RERA deadline. The project must deposit funds in an escrow account per RERA norms, ensuring construction is not entirely dependent on new bookings. Verify the RERA compliance status before booking." },
      { question: "How does Royce compare to Marbella Grand, which is by the same group?", answer: "Marbella Grand (Sector 82A) is the established project — delivered, with 800+ units and a mature community. It is the reference point. Royce is the \"ultra-luxury evolution\" — fewer units, bigger apartments, taller towers, designer-led architecture, and a later timeline. Grand is for buyers who want to move into a working community soon. Royce is for buyers who want the trophy asset and can wait until 2030." },
      { question: "Is the Marbella Group financially capable of delivering a 42-floor tower?", answer: "Marbella Grand is successfully delivered and occupied — the group has execution capability. However, a 42-floor tower is structurally more complex than Grand's 23-floor towers. Construction finance, structural engineering, and timeline management on a project of this height warrant close monitoring. Request quarterly construction updates and verify RERA milestone compliance before each payment tranche." }
    ]
  },
  {
    slug: "marbella-grand",
    og_title: "Marbella Grand Mohali | 3+1/4+1 BHK IT City Sector 82A",
    og_description: "Marbella Grand — award-winning eco luxury in Sector 82A Mohali. 5 min to airport. 3+1/4+1 BHK + Earth Villas. Times Business 2024. IGBC certified. From ₹3.10 Cr.",
    description: `Marbella Grand is the most discussed luxury residential project in Mohali's IT City belt — and for good reason. Spread across 11.12 acres in Sector 82A with 10 towers of 23 floors, it holds 822 units ranging from 3+1 BHK apartments to Sky Villas and Earth Villas. It is 5 minutes from Chandigarh International Airport and sits behind the Wipro SEZ, with ISB, IISER, and IT City all within 10 minutes.\n\nThe project won the Times Business 2024 award for eco-friendly construction. It carries IGBC certification and implements rainwater harvesting, solar lighting, natural ventilation roofing, and EV charging infrastructure. These are functioning systems, not architectural promises.\n\nResale market data is unambiguous: 3 BHK units are transacting at ₹2.5-3 Cr. Property prices in Sector 82 rose 14.4% year-on-year. Reddit discussions have identified this as one of the Mohali assets with the most active NRI investor interest in 2025-26. Maintenance is estimated at ₹3.5-5 per sq. ft. per month — higher than average, but buyers on the ground describe the pool, gym, and common areas as kept in "showroom condition."\n\nThe 50,000 sq. ft. clubhouse includes a mini theatre, spa, car wash, sky-gym, sky-walk, amphitheatre, pet park, driver's dormitory, and a library. These are verified from the project's RERA-filed documents and on-site reports.`,
    upcoming_infrastructure: [
      "IT City Expansion: The IT City cluster is directly behind Wipro SEZ. With IT City's commercial footprint expanding through 2026-28, demand for residential inventory within 5-10 minutes of campus will sustain and grow. Marbella Grand is the primary address in this range.",
      "Airport Proximity Premium: At 5 minutes from the airport, Marbella Grand benefits from any increase in airport traffic, NRI activity, and airline route expansion. International route additions directly raise the demand from NRI buyers who value airport proximity above almost all other factors.",
      "Aerocity Demand Corridor: GMADA Aerocity's ongoing development 10 minutes from the site continues to attract premium retail, hospitality, and office space — which will lift the lifestyle quotient of the Sector 82A address.",
      "200ft Airport Road Maturation: The Airport Road corridor from Sector 66 to Sector 83A is now a fully formed luxury residential belt. Land values in this stretch are on a structural upward trajectory given the lack of available undeveloped land."
    ],
    faqs: [
      { question: "Resale 3 BHK units are at ₹2.5-3 Cr. Is there still appreciation upside?", answer: "Sector 82 prices rose 14.4% in one year — above the Mohali average. The structural case for further appreciation is strong: airport proximity, IT City growth, IGBC certification differentiating it from generic stock, and active NRI interest. However, at ₹2.5-3 Cr, buyers must evaluate carefully — overpaying in a mature market reduces the margin for error. Negotiate on the specific unit and floor rather than accepting list price." },
      { question: "What are the actual maintenance costs and are they sustainable?", answer: "₹3.5-5 per sq. ft. per month translates to approximately ₹9,000-13,000 monthly for a 2,600 sq. ft. unit. Reviews confirm this money is visibly spent on the pool, gym, and common area quality. The maintenance fund is managed by the RWA. Verify the fund's balance and any pending dues from the society before buying in resale." },
      { question: "How is the building's seismic resilience — it is a 23-floor RCC structure?", answer: "The towers are built with an RCC framed structure compliant with Seismic Zone IV specifications — the highest risk zone applicable in this region. For buyers concerned about Himalayan foothills seismic activity, Zone IV compliance is the standard required by the National Building Code. The Mivan construction method also contributes to lateral load resistance." },
      { question: "Is there any waterlogging or drainage issue in Sector 82A during monsoon?", answer: "99acres locality reviews note periodic waterlogging on Airport Road and stray cattle as concerns for Sector 82. Within Marbella Grand's campus, the site engineering and drainage appears adequate based on resident feedback. The public road in front of the project is the area of concern, not the internal campus." }
    ]
  },
  {
    slug: "jlpl-sky-garden",
    og_title: "JLPL Sky Garden | 2+1 BHK, Sector 66A Mohali",
    og_description: "JLPL Sky Garden — ready-to-move 2+1 BHK in Sector 66A Mohali. 65,000 sq.ft. eco-deck, TEAM-3 Singapore design. Resale from ₹61 lakh. Near airport and railway.",
    description: `JLPL Sky Garden is the most accessible address in Mohali's premium Airport Road corridor. Designed by TEAM-3 Architects Singapore — the same firm behind Chandigarh's contemporary landmarks — the project comprises 11 G+13 towers of 528 apartments in 2+1 BHK configurations, all within the 262.69-acre Super Mega Mixed Use Integrated Industrial Park developed by JLPL.\n\nThe project is fully ready to move. Units are available in resale from ₹61 lakh to ₹67 lakh — making this the most affordable entry point into the Sector 66A corridor, where adjacent luxury projects like JLPL Falcon View command multiples of this price. The adjacency to Falcon View is an asset: Sky Garden residents share the broader JLPL-developed infrastructure, including planned commercial zones, Bestech Business Tower access, and the IT City commute corridor.\n\nThe design reflects genuine architectural investment: 7ft 6in glazing, double-height sky decks per tower, 65,000+ sq. ft. eco-deck with 200+ tree species, and 5,000 sq. ft. clubhouse. The eco-deck is not a rooftop garden — it is an elevated green landscape at deck level, separating pedestrian and residential space from vehicular activity.\n\nWith ~95% occupancy and active resale listings, this is the most liquid residential product in the immediate area. For buyers entering the Airport Road corridor on a sub-₹70 lakh budget, Sky Garden is the only genuine option.`,
    upcoming_infrastructure: [
      "Rail and Airport Corridor Demand: Sector 66A sits between the Mohali Railway Station and Chandigarh International Airport — within 10 minutes of both. As rail frequency and airport routes increase, demand for residential within this twin-connectivity corridor will rise.",
      "JLPL Industrial Park Maturation: The 262.69-acre JLPL Super Mega project that Sky Garden is part of includes IT complexes, business centres, 5-star and 4-star hotels, and a convention centre. As these components deliver over 2026-30, the immediate address value of Sky Garden will improve.",
      "IT City Commercial Spillover: Bestech Business Tower (2km) and the IT City main campus are within the same commute zone. As IT City expands, the rental catchment for Sky Garden — targeting professionals who cannot yet afford Sector 66 luxury — deepens.",
      "Ongoing Resale Liquidity: Sector 66A has the most active resale market among the JLPL projects, with 32+ active listings on 99acres at any given time. This liquidity is itself an infrastructure — it means buyers can exit without distress."
    ],
    faqs: [
      { question: "Sky Garden towers are G+13, not G+14 as listed in some places. What is the correct count?", answer: "Official brochures and RERA documents confirm G+13 towers (14 floors including ground). Some listings show 12 floors — this refers to residential floors excluding ground. The correct description is 11 towers of G+13 = 14 floors total. Verify the specific flat's floor level against the RERA-approved building plan." },
      { question: "Name is listed as \"Sky Garden\" on your website but \"Sky Gardens\" on RERA. Which is correct?", answer: "RERA registration PBRERA-SAS81-PR0199 is registered as \"Sky Gardens\" (plural). Both names refer to the same project. For SEO and formal documents, use \"Sky Gardens.\" In common parlance, both are in use." },
      { question: "At ₹61-67 lakh resale, is this genuinely a good investment or is it the budget option for a reason?", answer: "It is both. The budget pricing reflects the smaller unit size (1,345-1,431 sq. ft.) and the 2+1 BHK configuration — not a location or quality compromise. The building quality (TEAM-3 architecture, Mivan construction, earthquake resistant) is equivalent to premium projects. For a first-time buyer or investor seeking rental yield in the IT corridor, Sky Garden offers the best risk-adjusted entry. Rental yield for a 2+1 BHK here runs ₹12,000-16,000 per month — a 2.4-3.1% gross annual yield on ₹65 lakh invested." },
      { question: "Is the society well-managed with 95% occupancy?", answer: "High occupancy is a double-edged signal. It confirms demand and community vitality, but it also means the common areas — pool, gym, elevator — are heavily used. Resident reviews are generally positive about security and common area maintenance, but describe the club as functional rather than luxurious, which is accurate for a 5,000 sq. ft. space serving 500+ units." }
    ]
  },
  {
    slug: "ananda-crown",
    og_title: "Ananda Crown Mohali | Luxury 3/4 BHK Apartments, Sector 78",
    og_description: "Ananda Crown, Sector 78 Mohali — upcoming ultra-luxury 3BHK/3+1/4+1 apartments from ₹3.05 Cr. Near PCA Stadium and Hockey Stadium. Gated, low-density.",
    description: `Ananda Crown is Sector 78's first luxury high-rise entry at this price point. The project occupies a prime residential position in Sector 78 — a sector that residents rate 4.5 out of 5 for environment, cleanliness, and neighbourliness — and offers 3 BHK (3,050 sq. ft.), 3+1 BHK, and 4+1 BHK (3,750 sq. ft.) apartments across 4 towers.\n\nThe unit sizes are large by any standard. A 3,050 sq. ft. 3 BHK here costs ₹3.05 Cr — that is significantly more floor space per rupee than equivalent 3 BHK options in Sector 66 or 83A, where ₹3 Cr buys you 1,700-2,000 sq. ft. in most projects. For buyers who prioritise space over postcode prestige, this is a meaningful value proposition.\n\nSector 78 sits 10 minutes from Mohali International Hockey Stadium, 10 minutes from PCA Cricket Stadium (I.S. Bindra Stadium), and 10 minutes from Chandigarh International Airport. The sector connects easily to Sector 79 and the Sohana commercial belt. Field reviews describe Sector 78 as well-maintained and peaceful compared to the denser Airport Road corridor.\n\nAnanda Group is an established developer — they have delivered residential and commercial projects in the construction space for over a decade. This is their significant Mohali launch. Given the limited online track record specific to Mohali, buyers should visit the site, verify RERA registration and construction progress, and ask for details of completed projects in other markets.`,
    upcoming_infrastructure: [
      "Sector 78 Residential Densification: Sector 78 is mid-development. With a strong resident rating (4.5/5 locally) and growing residential projects, the sector is tracking toward the premium residential cluster status that Sector 88 achieved 5-7 years ago. Early investment in a sector with improving fundamentals is where appreciation is highest.",
      "Sports Infrastructure Proximity: The Mohali International Hockey Stadium and PCA Cricket Stadium bring national-level sporting events to the immediate neighbourhood. These venues attract hospitality, retail, and media investment — all of which improve the quality-of-life premium of residential addresses nearby.",
      "Airport Road (PR-7) Access Improvement: Sector 78's connectivity to Airport Road is set to improve through planned GMADA road upgrades connecting the inner sectors to PR-7. This will reduce the commute gap between Sector 78 and the primary IT and Airport corridor.",
      "Premium Residential Spillover: As core sectors (66, 77, 83A, 88) saturate, buyers and developers are identifying Sector 78 as the next premium tier. Ananda Crown's launch is one signal of this shift. Early buyers in this trend typically benefit most."
    ],
    faqs: [
      { question: "This is a new project with limited online reviews. How do I evaluate the risk?", answer: "Three checks. First, verify the RERA registration on Punjab RERA portal — confirm construction stage milestones are being met. Second, visit Ananda Group's completed projects in their home market (they are Bangalore-based) and speak to buyers there. Third, cross-reference with local Mohali brokers who can share site-level construction observations. New projects with limited track record warrant extra diligence, not automatic avoidance." },
      { question: "How does ₹3.05 Cr for 3,050 sq. ft. in Sector 78 compare to similar pricing in Sector 88?", answer: "In Sector 88, ₹3 Cr buys approximately 2,000-2,200 sq. ft. In Ananda Crown, it buys 3,050 sq. ft. — nearly 40% more space. The trade-off is location maturity: Sector 88 (Hero Homes, Horizon Belmond, Joy Grand) is a more established residential address with better rental yield history. If space is the priority, Ananda Crown wins. If location liquidity is the priority, Sector 88 wins." },
      { question: "What is the possession timeline?", answer: "The project is listed as under construction with no publicly confirmed RERA possession date visible on major property platforms as of May 2026. Obtain the RERA registration number from the developer and verify the PBRERA portal for the committed delivery date before paying any booking amount." },
      { question: "No floor plan or brochure download on your website — is this available?", answer: "A brochure should be added to the listing. For buyers, the floor plan and RERA-approved building plan are documents you have a right to before booking. Request them from the developer and do not proceed without reviewing the carpet area calculation and layout." }
    ]
  },
  {
    slug: "joy-grand",
    og_title: "Joy Grand Mohali | 3+1/4+1 BHK High-Rise, Sector 88 Mohali",
    og_description: "Joy Grand — luxury 3+1 and 4+1 BHK in Sector 88 Mohali. 7 blocks up to 26 floors. Both-sides-open. Mini clinic on-site. Mivan construction. From ₹2.28 Cr.",
    description: `Joy Grand is a high-rise residential complex by Joy Homes in Sector 88, Mohali — built by a developer with a specific and verifiable track record: timely possession of Joy Homes and Joy Smart Homes at Sector 85, where families are already residing. In a market full of first-time luxury developers, that distinction matters.\n\nThe project spans approximately 6.5 acres with 7 blocks in a configuration you rarely see: single-lane layouts with both sides open on every flat. This means every apartment in Joy Grand has two open faces — guaranteed natural light and cross-ventilation regardless of which floor or block you select. The blocks are staggered: 3 blocks at 26 floors, 2 at 25 floors, 2 at 18 floors. Upper-floor units in the 26-floor towers have unobstructed views of GMADA green belts and the distant Shivalik hills.\n\nThe project includes a feature that is genuinely rare in Mohali residential: an on-site mini clinic. For families with elderly members or young children, this is not a luxury extra — it is a practical differentiator that reduces the friction of minor medical needs without leaving the campus.\n\nCentralised AC is standard in all units. Mivan construction is used throughout. Rainwater harvesting is built into the structure. The project is RERA-registered. Joy Grand is 9.5 km from the airport (7 minutes by car to Chandigarh), 10 minutes from ISB, and 10 minutes from PCA Stadium.`,
    upcoming_infrastructure: [
      "Sector 88 as Mohali's Established Luxury Zone: Sector 88 now hosts Hero Homes (delivered), Horizon Belmond (delivering 2027), and Joy Grand — an established cluster of premium projects that collectively anchor the sector's premium residential identity. This cluster dynamic pushes services, schools, and retail toward the sector.",
      "Mohali Railway Station Connectivity: Joy Grand is 5.35 km from Mohali Railway Station. Proposed rail upgrades and RRTS corridor studies for the Chandigarh-Mohali belt would make this proximity a meaningful commute advantage.",
      "Sector 88 Smart City Infrastructure: Planned installation of centralised smart metering, 66KV sub-stations, and advanced storm-water drainage for Sector 88 is in the GMADA forward plan. This will address the infrastructure gap that currently exists and raise the sector's liveability rating.",
      "Airport Road Linkage: Joy Grand's internal road connects directly to Airport Road, providing a signal-free corridor toward the airport in one direction and toward ISB, IT City, and CP67 in the other."
    ],
    faqs: [
      { question: "Joy Homes delivered Sector 85 projects on time. Is Joy Grand on the same track?", answer: "The developer publicly references timely delivery of Joy Homes and Joy Smart Homes at Sector 85 as their credibility anchor. This is verifiable — visit Sector 85 and speak to residents. The question for Joy Grand is whether a 26-floor high-rise project at 6.5 acres is in the same complexity class as the earlier Sector 85 delivery. High-rise timelines are structurally longer. Do not assume Sector 85 delivery speed will translate directly to Joy Grand." },
      { question: "What does \"both-sides-open\" actually mean — and why does it matter?", answer: "A standard apartment in a multi-tower project typically has one open face (external wall) and the other faces share a corridor or an adjacent tower. Joy Grand's single-lane layout means each flat is positioned like a row house — open air on both sides. This delivers more natural light, better cross-ventilation, less noise transfer from neighbours, and a more spacious feel regardless of the unit's actual square footage." },
      { question: "Is the mini clinic on-site actually functional or is it a promised amenity?", answer: "The mini clinic is listed in the project's official RERA-filed amenity schedule. It is positioned as an on-site first-response medical facility — not a full hospital. For families with elderly parents or young children, it handles minor injuries, routine check-ups, and emergencies before transfer to a full hospital (Fortis and Max are both within 10-15 minutes). Verify its operational status during your site visit." },
      { question: "With no brochure download on the current listing, where can buyers get floor plans?", answer: "Request directly from the Joy Homes sales office. Also, the RERA-registered building plan is a public document — the RERA number can be used to pull the sanctioned floor plans from the Punjab RERA portal. A brochure download link should be added to the listing page — this is a gap in the current property page." }
    ]
  }
];

async function updateSEO() {
  console.log("Starting bulk SEO update...");

  for (const item of seoData) {
    console.log(`Updating ${item.slug}...`);
    
    // We update apartments since these are all apartments. 
    // Just in case Jubilee City Gardens is in lands, we can check.
    let targetTable = "apartments";
    let check = await supabase.from("apartments").select("id").eq("slug", item.slug).single();
    if (!check.data) {
      check = await supabase.from("lands").select("id").eq("slug", item.slug).single();
      if (check.data) targetTable = "lands";
      else {
        check = await supabase.from("houses").select("id").eq("slug", item.slug).single();
        if (check.data) targetTable = "houses";
      }
    }

    if (!check.data) {
      console.warn(`Could not find record with slug ${item.slug} in any table.`);
      continue;
    }

    const { error } = await supabase
      .from(targetTable)
      .update({
        og_title: item.og_title,
        og_description: item.og_description,
        meta_description: item.og_description,
        description: item.description,
        upcoming_infrastructure: item.upcoming_infrastructure,
        faqs: item.faqs
      })
      .eq("slug", item.slug);

    if (error) {
      console.error(`Error updating ${item.slug}:`, error);
    } else {
      console.log(`Successfully updated ${item.slug} in ${targetTable}.`);
    }
  }
  console.log("Finished bulk SEO update.");
}

updateSEO();
